#!/usr/bin/env python3
"""Run the HS3 corpus comparison tests and print formatted tables.

Two comparisons, one per corpus flavour:

  - Fixtures (corpora/hs3/fixtures): FlatPPL 2DeltaNLL vs the frozen RooFit
    expected vector, per scan point.
  - Conversions (corpora/hs3/conversions): the committed FlatPPL paper examples,
    scored over their theta points vs the frozen ROOT 2DeltaNLL vector
    (generated by conversions/gen_expected.py).

Requires the converter (FLATPPL_BIN) and the JS engine (FLATPPL_JS_DIR); both
have defaults in config.py. Run via `pixi run hs3`, or directly:
`python corpora/hs3/run_comparisons.py`.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HS3_ROOT = Path(__file__).resolve().parent       # corpora/hs3
REPO = HS3_ROOT.parents[1]                        # repo root
sys.path.insert(0, str(REPO / "src"))

from flatppl_testsuite.suites.hs3_import import (  # noqa: E402
    score_scan, score_points, HS3_CORPUS, HS3_MANIFEST)
from flatppl_testsuite.formats.hs3.importer import SkipUnimplemented  # noqa: E402


def _fixtures_tables() -> bool:
    print("=" * 78)
    print("FIXTURES — 2DeltaNLL: FlatPPL vs frozen RooFit   (corpora/hs3/fixtures)")
    print("=" * 78)
    manifest = json.loads(HS3_MANIFEST.read_text())
    ok_all = True
    for fx in manifest["fixtures"]:
        fdir = HS3_CORPUS / fx["path"]
        hs3_path = fdir / "hs3.json"
        hs3_doc = json.loads(hs3_path.read_text())
        expected_doc = json.loads((fdir / "expected.json").read_text())
        for check in expected_doc["checks"]:
            if check["kind"] != "twice_delta_nll_scan":
                continue
            sp, pts = check["scan_parameter"], check["scan_points"]
            exp, tol = check["expected"], check["tolerance"]
            print(f"\n{fx['test_id']} :: {check['id']}   (scan {sp})")
            try:
                got = score_scan(hs3_doc, hs3_path, check)
            except SkipUnimplemented as e:
                print(f"  SKIPPED — unimplemented HS3 construct: {e.hs3_type}")
                continue
            except Exception as e:  # noqa: BLE001
                print(f"  UNSCOREABLE — {e}")
                ok_all = False
                continue
            print(f"  {sp:>8} | {'expected':>18} | {'got':>18} | {'|delta|':>10} | result")
            print(f"  {'-'*8}-+-{'-'*18}-+-{'-'*18}-+-{'-'*10}-+-------")
            check_ok = True
            for v, e, g in zip(pts, exp, got):
                d = abs(g - e)
                hit = d <= tol["atol"] + tol["rtol"] * abs(e)
                check_ok &= hit
                print(f"  {v:>8} | {e:>18.10g} | {g:>18.10g} | {d:>10.3e} | "
                      f"{'PASS' if hit else 'FAIL'}")
            ok_all &= check_ok
            print(f"  => {'PASS' if check_ok else 'FAIL'}  "
                  f"(atol={tol['atol']:g}, rtol={tol['rtol']:g})")
    return ok_all


def _conversions_tables() -> bool:
    print("\n" + "=" * 78)
    print("CONVERSIONS — FlatPPL vs frozen ROOT 2DeltaNLL   (corpora/hs3/conversions)")
    print("=" * 78)
    manifest = json.loads(HS3_MANIFEST.read_text())
    ok_all = True
    for conv in manifest.get("conversions", []):
        conv_dir = HS3_CORPUS / conv["path"]
        expected_doc = json.loads((conv_dir / "expected.json").read_text())
        model_file = conv_dir / expected_doc["model"]
        for check in expected_doc["checks"]:
            if check["kind"] != "twice_delta_nll_points":
                continue
            exp, tol = check["expected"], check["tolerance"]
            print(f"\n{conv['test_id']} :: {check['id']}   (binding {check['binding']})")
            try:
                got = score_points(model_file, check)
            except Exception as e:  # noqa: BLE001
                print(f"  UNSCOREABLE — {e}")
                ok_all = False
                continue
            print(f"  {'point':>6} | {'expected':>18} | {'got':>18} | {'|delta|':>10} | result")
            print(f"  {'-'*6}-+-{'-'*18}-+-{'-'*18}-+-{'-'*10}-+-------")
            check_ok = True
            for i, (e, g) in enumerate(zip(exp, got)):
                d = abs(g - e)
                hit = d <= tol["atol"] + tol["rtol"] * abs(e)
                check_ok &= hit
                print(f"  {i:>6} | {e:>18.10g} | {g:>18.10g} | {d:>10.3e} | "
                      f"{'PASS' if hit else 'FAIL'}")
            ok_all &= check_ok
            print(f"  => {'PASS' if check_ok else 'FAIL'}  "
                  f"(atol={tol['atol']:g}, rtol={tol['rtol']:g})")
    return ok_all


def main() -> int:
    fixtures_ok = _fixtures_tables()
    conversions_ok = _conversions_tables()
    return 0 if (fixtures_ok and conversions_ok) else 1


if __name__ == "__main__":
    sys.exit(main())
